export const DEFAULT_USER = {
  id: '',
  firstName: '',
  lastName: '',
  userName: '',
  email: '',
  street: '',
  building: '',
  city: '',
  zipcode: '',
  phone: '',
  website: '',
  companyName: '',
  companyScope: '',
};
